### ISSUE TITLE
Creación de API CRUD para consulta de tablas clasificadas como Organizaciones Externas

### ISSUE THREAD

**Issue by mariaortiz0401** [udistrital/organizaciones_externas#2]
Conforme a la revisión realizada sobre las 28 tablas relacionadas con variables globales, se decide crear un API que trate específicamente sobre organizaciones o entidades del estado y que permita la consulta de la información de la misma a todos los sistemas de la oficina. Este guardará su estructura definitiva y aprobada por los equipos de Arquitectura y Base de datos. Este API debe realizarse siguiendo los lineamientos de migraciones establecidos por la OAS. 

Criterios de aceptación:
- [ ] API en ambiente de pruevas que permita consumir esquema final

_Nota:_ Este API estará sujeto a modificaciones debido a posteriores análisis sobre las tablas en los distintos esquemas CORE.

**Comment by AlaskaRising** [comment]
En reunión el día de hoy se evidencia que el modelo requiere ajustes para evitar repetir modelos de tablas, se acordó usar un modelo relacional para reducir numero de tablas, por lo que se requiere cambiar el diseño para su posterior evaluación e implementación.

**Comment by AlaskaRising** [comment]
En el análisis preliminar se evidencio la necesidad de crear un repositorio para agrupar las organizaciones externas, se buscaba crear un modelo de 2 tablas donde se definieran los tipos de organizaciones, sin embargo al iniciar el análisis del esquema de personas se acordó en reunión con DBA y Arquitectura orientar personas y organizaciones, a un esquema de Terceros que soporte a los dos, por lo que este repositorio ya no es pertinente.
